<?php

declare(strict_types=1);

require_once __DIR__ . '/includes/bootstrap.php';

require_active_account();


/*
|--------------------------------------------------------------------------
| Blackthorne Academy
| Single Notification Redirect / Mark-Read Handler
|--------------------------------------------------------------------------
|
| This endpoint:
|
| 1. Loads one notification owned by the current user.
| 2. Marks it read.
| 3. Redirects to its stored internal Blackthorne Academy URL.
|
| It must never expose or modify another user's notification.
| It must never redirect to an external website.
|
*/


$userId =
    (int) current_user_id();


/*
|--------------------------------------------------------------------------
| Resolve Notification ID
|--------------------------------------------------------------------------
*/

$notificationReference =
    trim(
        (string) (
            $_GET['n']
            ?? ''
        )
    );

if (
    $notificationReference === ''
    || !ctype_digit(
        $notificationReference
    )
) {
    set_flash(
        'error',
        'That notification could not be found.'
    );

    redirect(
        url(
            'notifications.php'
        )
    );
}


$notificationId =
    (int) $notificationReference;

if ($notificationId <= 0) {
    set_flash(
        'error',
        'That notification could not be found.'
    );

    redirect(
        url(
            'notifications.php'
        )
    );
}


/*
|--------------------------------------------------------------------------
| Fetch Notification
|--------------------------------------------------------------------------
|
| Ownership is enforced directly in the query. A logged-in user cannot use
| this handler to read or manipulate somebody else's notification by changing
| the query-string ID.
|
*/

$notificationStatement =
    $pdo->prepare(
        'SELECT
            id,
            user_id,
            actor_user_id,
            notification_type,
            related_entity_type,
            related_entity_id,
            title,
            message,
            link_url,
            is_read,
            read_at,
            created_at

         FROM notifications

         WHERE id = :notification_id
           AND user_id = :user_id

         LIMIT 1'
    );

$notificationStatement->execute([
    'notification_id' =>
        $notificationId,

    'user_id' =>
        $userId,
]);

$notification =
    $notificationStatement->fetch(
        PDO::FETCH_ASSOC
    );


if (!is_array($notification)) {
    set_flash(
        'error',
        'That notification could not be found.'
    );

    redirect(
        url(
            'notifications.php'
        )
    );
}


/*
|--------------------------------------------------------------------------
| Mark Read
|--------------------------------------------------------------------------
|
| Preserve the original read_at timestamp if the notification was already
| opened previously.
|
*/

if (
    (int) (
        $notification['is_read']
        ?? 0
    ) !== 1
) {
    $markReadStatement =
        $pdo->prepare(
            'UPDATE notifications

             SET
                is_read = 1,
                read_at = COALESCE(
                    read_at,
                    NOW()
                )

             WHERE id = :notification_id
               AND user_id = :user_id'
        );

    $markReadStatement->execute([
        'notification_id' =>
            $notificationId,

        'user_id' =>
            $userId,
    ]);
}


/*
|--------------------------------------------------------------------------
| Safe Redirect Target
|--------------------------------------------------------------------------
|
| notification.link_url may contain:
|
| - A full URL generated by url(), such as:
|   https://blkthrnacad.com/thread.php?t=123
|
| - A root-relative internal path, such as:
|   /thread.php?t=123
|
| - A relative internal path, such as:
|   thread.php?t=123
|
| External hosts, protocol-relative URLs, backslashes, control characters,
| unsupported schemes, and malformed URLs are rejected.
|
*/

function blackthorne_notification_redirect_url(
    ?string $storedUrl
): string {
    $storedUrl =
        trim(
            (string) $storedUrl
        );

    $fallback =
        url(
            'notifications.php'
        );

    if ($storedUrl === '') {
        return $fallback;
    }


    /*
    |--------------------------------------------------------------------------
    | Reject dangerous URL forms
    |--------------------------------------------------------------------------
    */

    if (
        str_contains(
            $storedUrl,
            '\\'
        )
        || preg_match(
            '/[\x00-\x1F\x7F]/',
            $storedUrl
        ) === 1
        || str_starts_with(
            $storedUrl,
            '//'
        )
    ) {
        return $fallback;
    }


    /*
    |--------------------------------------------------------------------------
    | Root-Relative Internal URL
    |--------------------------------------------------------------------------
    */

    if (
        str_starts_with(
            $storedUrl,
            '/'
        )
    ) {
        return
            rtrim(
                APP_URL,
                '/'
            )
            . $storedUrl;
    }


    /*
    |--------------------------------------------------------------------------
    | Relative Internal URL
    |--------------------------------------------------------------------------
    |
    | A colon before any slash/question/hash would indicate a URI scheme.
    | Relative application links should not contain one.
    |
    */

    $parsedScheme =
        parse_url(
            $storedUrl,
            PHP_URL_SCHEME
        );

    if (
        $parsedScheme === null
        && !str_contains(
            $storedUrl,
            '://'
        )
    ) {
        return
            url(
                $storedUrl
            );
    }


    /*
    |--------------------------------------------------------------------------
    | Full Absolute URL
    |--------------------------------------------------------------------------
    |
    | Only http/https links pointing back to the same application host are
    | accepted.
    |
    */

    $targetParts =
        parse_url(
            $storedUrl
        );

    $appParts =
        parse_url(
            APP_URL
        );

    if (
        !is_array(
            $targetParts
        )
        || !is_array(
            $appParts
        )
    ) {
        return $fallback;
    }


    $targetScheme =
        strtolower(
            (string) (
                $targetParts['scheme']
                ?? ''
            )
        );

    $targetHost =
        strtolower(
            (string) (
                $targetParts['host']
                ?? ''
            )
        );

    $targetPort =
        isset(
            $targetParts['port']
        )
            ? (int) $targetParts['port']
            : null;


    $appScheme =
        strtolower(
            (string) (
                $appParts['scheme']
                ?? ''
            )
        );

    $appHost =
        strtolower(
            (string) (
                $appParts['host']
                ?? ''
            )
        );

    $appPort =
        isset(
            $appParts['port']
        )
            ? (int) $appParts['port']
            : null;


    if (
        !in_array(
            $targetScheme,
            [
                'http',
                'https',
            ],
            true
        )
        || $targetHost === ''
        || $appHost === ''
        || !hash_equals(
            $appHost,
            $targetHost
        )
        || $targetPort !== $appPort
    ) {
        return $fallback;
    }


    /*
     * APP_URL currently defines the application's canonical scheme. Require
     * the same scheme so notification links cannot downgrade HTTPS.
     */
    if (
        $appScheme !== ''
        && !hash_equals(
            $appScheme,
            $targetScheme
        )
    ) {
        return $fallback;
    }


    return $storedUrl;
}


$redirectUrl =
    blackthorne_notification_redirect_url(
        isset(
            $notification['link_url']
        )
            ? (string) $notification['link_url']
            : null
    );


redirect(
    $redirectUrl
);
